/*
SQLyog Ultimate v8.3 
MySQL - 5.6.28-cdb2016-log : Database - working
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;




/*Table structure for table `py_main_goodsorder` */

DROP TABLE IF EXISTS `py_main_goodsorder`;

CREATE TABLE `py_main_goodsorder` (
  `IDS` int(32) NOT NULL,
  `BIGORDER_ID` varchar(32) NOT NULL COMMENT '大订单id',
  `VENDOR_IDS` varchar(32) NOT NULL COMMENT '商户id',
  `USER_IDS` varchar(32) NOT NULL COMMENT '用户id',
  `CONT_IDENTITYNO` varchar(32) DEFAULT NULL COMMENT '收货人证件号',
  `CONT_POSTCODE` varchar(10) DEFAULT NULL COMMENT '邮箱',
  `CONT_ADDRESS` varchar(200) DEFAULT NULL COMMENT '详细地址',
  `CONT_MOBILE` varchar(11) DEFAULT NULL COMMENT '座机',
  `CONT_PHONE` varchar(20) DEFAULT NULL COMMENT '手机',
  `CONT_PROVINCE` varchar(50) DEFAULT NULL COMMENT '省',
  `CONT_CITY` varchar(30) DEFAULT NULL COMMENT '市',
  `CONT_DISTRICT` varchar(20) DEFAULT NULL COMMENT '区',
  `CONT_STREET` varchar(100) DEFAULT NULL COMMENT '街道',
  `DELIVERY_TIME` varchar(14) DEFAULT NULL COMMENT '格式如 9:00-18:00',
  `DELIVERY_WAY` varchar(100) DEFAULT '1' COMMENT '配送方式 1 快递 2 自提',
  `BUYERS_MESSAGE` varchar(1000) DEFAULT NULL COMMENT '留言',
  `ORDER_TIME` varchar(32) DEFAULT NULL COMMENT 'yyyy-mm-dd hh:mm:ss 下单时间',
  `SETTLE_TIME` varchar(14) DEFAULT NULL COMMENT '放款成功时间',
  `ISEVALUATE` varchar(1) DEFAULT NULL COMMENT '0 未评价 1 已评价',
  `DISCOUNT` decimal(14,2) DEFAULT NULL COMMENT '折扣',
  `ORDER_TOTAL_AMT` decimal(14,2) DEFAULT NULL COMMENT '商品总价',
  `ORDER_AMT` decimal(14,2) DEFAULT NULL COMMENT '实付现金',
  `SETTLE_AMT` decimal(14,2) DEFAULT NULL COMMENT '最终清算金额',
  `SETTLE_STATUES` varchar(5) DEFAULT NULL COMMENT '清算状态  0-未处理  1-成功 2-失败 3 清算中',
  `PAY_STATUS` varchar(5) NOT NULL COMMENT '0 未支付 1 已支付  2 取消',
  `STATUS` varchar(5) NOT NULL COMMENT '订单状态：0001-待付款 0002-待发货 0003-已发货 0004-交易成功 0005-售后处理中 0006-订单关闭 0007-交易关闭 0008-交易完成  0009-退款中',
  `APPROVE_STATUS` varchar(4) DEFAULT NULL COMMENT '售后状态0101-待商家确认0102-待买家寄回0103-待确认质检0104-退款中0105-退款成功0106-退款关闭0107-换货成功0108-换货关闭',
  `PAYWAY` varchar(15) DEFAULT NULL COMMENT '支付方式 1 微信',
  `TRANSACTIONID` varchar(32) DEFAULT NULL COMMENT '订单流水号',
  `CONT_NAME` varchar(50) DEFAULT NULL COMMENT '联系人',
  `SETTLE_BATCH_NO` varchar(32) DEFAULT NULL,
  `WX_FEE` decimal(14,2) DEFAULT NULL,
  `SETTLE_STATUS_FEE` varchar(5) DEFAULT NULL,
  `SETTLE_TIME_FEE` varchar(14) DEFAULT NULL,
  `SETTLE_BATCH_NO_FEE` varchar(32) DEFAULT NULL,
  `PAY_TIME` varchar(14) DEFAULT NULL COMMENT 'yyyymmddhhmiss 支付时间',
  `Sign_time` varchar(14) DEFAULT NULL COMMENT '签收时间',
  `IS_TICKET` varchar(32) DEFAULT '0' COMMENT '优惠卷唯一串码，未使用默认值是0',
  `logistics_company_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '物流公司编号',
  `logistics_company_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '物流公司名称',
  `express_no` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '快递单号',
  `IS_INVOICE` varchar(1) DEFAULT NULL COMMENT '是否需要发票:1－是 0－否',
  `INVOICE` varchar(200) DEFAULT NULL COMMENT '发票抬头',
  `INVOICE_CONTENT` varchar(250) DEFAULT NULL COMMENT '发票内容',
  `delete_status` varchar(1) DEFAULT NULL COMMENT '删除状态0-正常，1-删除',
  `brand_info_ids` varchar(32) DEFAULT NULL COMMENT '品牌ids',
  `customerPhone` varchar(32) DEFAULT NULL COMMENT '客户账号',
  `is_send` varchar(1) DEFAULT '0' COMMENT '是否已经发送快递100请求，0--没有，1--已发送',
  `is_makeloan` varchar(1) DEFAULT '0' COMMENT '是否已放款 0-未放款 1-已放款',
  `CUSTOMER_NAME` varchar(64) DEFAULT '客户姓名',
  `REFUNDSTATUS` varchar(4) DEFAULT NULL COMMENT '0001：申请退款撤单 0002：退款撤单通过 0003：退款撤单拒绝',
  `REFUNDUSER` varchar(20) DEFAULT NULL COMMENT '买家 - 卖家',
  `STOCKSTATUS` varchar(1) DEFAULT '0' COMMENT '是否缺货 0为正常  1为缺货',
  `ISLOCK` varchar(1) DEFAULT '0' COMMENT '是否锁定订单 0为解锁 1为锁定',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATER` varchar(20) DEFAULT NULL COMMENT '创建人',
  `MODIFY_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  `MODIFIER` varchar(20) DEFAULT NULL COMMENT '修改人',
  `MARK` varchar(200) DEFAULT NULL COMMENT '备注',
  `REFUND_TIME` varchar(32) DEFAULT NULL COMMENT '退款时间',
  `SETTLEMENT_TIME` varchar(32) DEFAULT NULL COMMENT '结算时间',
  `SETTLEMENT_IDS` varchar(32) DEFAULT NULL COMMENT '结算单号',
  PRIMARY KEY (`IDS`),
  KEY `IDX_MIANGOODSORDER_NAME` (`CONT_NAME`),
  KEY `IDX_MIANGOODSORDER_PHONE` (`CONT_PHONE`),
  KEY `IDX_MIANGOODSORDER_PSTATUS` (`PAY_STATUS`),
  KEY `IDX_MIANGOODSORDER_STATUS` (`STATUS`),
  KEY `IDX_MIANGOODSORDER_TIME` (`SETTLE_TIME`),
  KEY `IDX_MIANGOODSORDER_TRAN` (`TRANSACTIONID`),
  KEY `IDX_MIANGOODSORDER_VEND` (`VENDOR_IDS`),
  KEY `idx_goodsorder_transactionid_bigorderid` (`BIGORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `py_main_goodsorder` */

insert  into `py_main_goodsorder`(`IDS`,`BIGORDER_ID`,`VENDOR_IDS`,`USER_IDS`,`CONT_IDENTITYNO`,`CONT_POSTCODE`,`CONT_ADDRESS`,`CONT_MOBILE`,`CONT_PHONE`,`CONT_PROVINCE`,`CONT_CITY`,`CONT_DISTRICT`,`CONT_STREET`,`DELIVERY_TIME`,`DELIVERY_WAY`,`BUYERS_MESSAGE`,`ORDER_TIME`,`SETTLE_TIME`,`ISEVALUATE`,`DISCOUNT`,`ORDER_TOTAL_AMT`,
`ORDER_AMT`,`SETTLE_AMT`,`SETTLE_STATUES`,`PAY_STATUS`,`STATUS`,`APPROVE_STATUS`,`PAYWAY`,`TRANSACTIONID`,`CONT_NAME`,`SETTLE_BATCH_NO`,`WX_FEE`,`SETTLE_STATUS_FEE`,`SETTLE_TIME_FEE`,`SETTLE_BATCH_NO_FEE`,`PAY_TIME`,`Sign_time`,`IS_TICKET`,`logistics_company_id`,`logistics_company_name`,`express_no`,`IS_INVOICE`,`INVOICE`,
`INVOICE_CONTENT`,`delete_status`,`brand_info_ids`,`customerPhone`,`is_send`,`is_makeloan`,`CUSTOMER_NAME`,`REFUNDSTATUS`,`REFUNDUSER`,`STOCKSTATUS`,`ISLOCK`,`CREATE_TIME`,`CREATER`,`MODIFY_TIME`,`MODIFIER`,`MARK`,`REFUND_TIME`,`SETTLEMENT_TIME`,`SETTLEMENT_IDS`) 
values (1,'1','001','1','123456','52324','广东',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(2,'321','sh01','ky01','65328','24524','深圳','421','1131',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(3,'111','sh02','yh02','00091','421424','宝安','222','2313',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(4,'234','sh03','yh03','890001','647224','西乡','332','423131',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(5,'b21','sh04','yh04','79002','972342','长沙',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6,'b32','sh05','yh05','5335353','536786','哈尔滨',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(7,'b55','sh06','yh09','8446464','3647475','武汉',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(8,'b111','sh89','yh11','643643','647474','雨花区',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(9,'b4252','sh252','yh6464','585343','970453','召唤师峡谷',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(10,'b331','sh422','yh8575','42522','69686','宝气',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(11,'b42','sh6363','yh23242','75858','85853','z',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','客户姓名',NULL,NULL,'0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
